server:
  port: 20001
  name: go-sweet

sweet:
  mysql:
    host: 192.168.253.130
    port: 3306
    user: root
    password: 123456
    dbName: go_sweet_db
    maxIdleConns: 50 # 最大空闲连接数
    maxOpenConns: 100 # 最大打开连接数

  redis:
    host: 192.168.253.130
    port: 6379
    password: 123456 # 若没有密码，则不用填该项
    database: 2

  adx:
    host: https://your.adx.com
    appId: your_app_id
    appKey: your_app_key
    authorityID: your_authority_id

  mqtt:
    host: 192.168.1.17
    port: 1883
    user: admin
    password: 123456

  logging:
    level: info
    file: log/go_sweet.log # 日志文件路径 必填
    maxSize: 10 # 单个日志文件最大大小，单位：MB
    maxDays: 30 # 单个日志文件保存天数
    maxBackups: 10 # 最大备份日志文件数量

  img:
    mappingUrl: /static # 映射的url 参考Tomcat映射图片地址配置
    path: D:/imgs
    baseUrl: http://localhost:20001


