server:
  port: 20001
  name: go-sweet

sweet:
  mysql:
    host: 192.168.251.19
    port: 3306
    user: root
    password: 123456
    dbName: sweet_test
    maxIdleConns: 50 # 最大空闲连接数
    maxOpenConns: 100 # 最大打开连接数
    logActive: true # 是否打印sql语句 , 若为false ,则可默认不写

  redis:
    host: 192.168.251.3
    port: 6379
    password: 123456 # 若没有密码，则不用填该项
    database: 5

  logging:
    level: info
    adapters: # 日志输出适配器
      - console # 输出到控制台 , 若仅输出到控制台 , 则无需配置其他配置

  img:
    mappingUrl: /static # 映射的url 参考Tomcat映射图片地址配置
    path: D:/imgs
    baseUrl: http://localhost:20001


